"""Loads card and crew board data generated by scripts/build_content.py.

The data is read-only and shared by every game. Card behaviour lives in card code
(see CLAUDE.md); this module only holds printed data.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Literal

import yaml
from pydantic import BaseModel, ConfigDict, Field

CONTENT_DIR = Path(__file__).resolve().parent.parent / "content"

Suit = Literal[
    "Person", "Cargo", "Ship", "Ally", "Encounter", "Incident", "Location",
    "Directive", "Captain", "Status", "Stardate",
]
Specialty = Literal["research", "influence", "military"]
MARKET_SUITS: tuple[Suit, ...] = ("Person", "Cargo", "Ship", "Ally")


class Operation(BaseModel):
    model_config = ConfigDict(frozen=True)

    kind: str
    text: str | None = None
    action_cost: bool = False
    attack: bool = False
    requires: str | None = None
    cost: str | None = None
    trigger: str | None = None
    uses: tuple[str, ...] = ()
    undoable: bool | None = None


class Card(BaseModel):
    model_config = ConfigDict(frozen=True)

    id: str
    name: str
    suit: Suit
    set: str
    deck: str  # Crew deck id, or "common"
    set_code: str
    box_marker: Literal["duplicate", "replacement"] | None = None
    position: str | None = None
    traits: tuple[str, ...] = ()
    skills: tuple[str, ...] = ()
    focus: str | None = None
    vp: int | str | None = None  # int, or a string such as "?" or "-?*"
    away_teams: int | str | None = None
    development_cost: str | None = None
    ship_token: bool = False
    image: str
    text: tuple[str, ...] = ()
    operations: tuple[Operation, ...] = ()
    # Stardate cards only
    mode: str | None = None
    sequence: int | None = None
    starting_glory: int | None = None
    bot_actions: int | None = None

    @property
    def is_common(self) -> bool:
        return self.deck == "common"


class Mission(BaseModel):
    model_config = ConfigDict(frozen=True)

    id: str
    name: str
    vp: int | None = None
    goal: str | None = None
    reward: str | None = None
    uses: tuple[str, ...] = ()


class Board(BaseModel):
    model_config = ConfigDict(frozen=True)

    id: str
    captain: str
    side: Literal["basic", "advanced"]
    image: str
    control_max: int
    actions: int
    mission_completion_tokens: int
    tracks: dict[Specialty, dict[int, int]]  # empty for Khan, who has no Specialty tracks
    trait_slots: int | None = None  # Khan only
    missions: tuple[Mission, ...] = Field(min_length=1)

    def multiplier(self, specialty: Specialty, highest_space: int) -> int:
        """Highest multiplier at or below the highest space reached (REQ-SP-04). Zero if none."""
        reached = [m for space, m in self.tracks.get(specialty, {}).items() if space <= highest_space]
        return max(reached, default=0)


class Content(BaseModel):
    model_config = ConfigDict(frozen=True)

    cards: dict[str, Card]
    boards: dict[str, Board]

    def by_set(self, *sets: str) -> list[Card]:
        return [c for c in self.cards.values() if c.set in sets]

    def crew_deck(self, deck: str) -> list[Card]:
        return [c for c in self.cards.values() if c.deck == deck]

    def board(self, captain: str, side: str) -> Board:
        # Khan has a single board with no side in its id.
        return self.boards.get(f"cb-{captain}-{side}") or self.boards[f"cb-{captain}"]

    def stardates(self, mode: str) -> list[Card]:
        return sorted((c for c in self.cards.values() if c.suit == "Stardate" and c.mode == mode), key=lambda c: c.sequence or 0)


def load_content(content_dir: Path = CONTENT_DIR) -> Content:
    cards: dict[str, Card] = {}
    for path in sorted((content_dir / "cards").glob("*.yaml")):
        data = yaml.safe_load(path.read_text())
        for raw in data["cards"]:
            card = Card(set=data["set"], **raw)
            if card.id in cards:
                raise ValueError(f"Duplicate card id {card.id} in {path.name}")
            cards[card.id] = card
    boards_data = yaml.safe_load((content_dir / "boards.yaml").read_text())
    boards = {b["id"]: Board(**b) for b in boards_data["boards"]}
    return Content(cards=cards, boards=boards)


@lru_cache
def content() -> Content:
    return load_content()
