#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["pyyaml>=6.0"]
# ///
"""Build the server's card and board data from the specs.

Reads   resources/scans/cards/**/*.md     card specs (see resources/scans/CARD_SPEC.md)
        resources/scans/boards/*.md       crew board specs
Writes  server/content/cards/<set>.yaml   one file per set
        server/content/boards.yaml        every crew board side

The specs are the source of truth. Never edit the generated files by hand; change the spec
and run this script again. It stops with an error if a spec is missing required data.

Usage:  scripts/build_content.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CARD_SPECS = ROOT / "resources" / "scans" / "cards"
BOARD_SPECS = ROOT / "resources" / "scans" / "boards"
OUT_CARDS = ROOT / "server" / "content" / "cards"
OUT_BOARDS = ROOT / "server" / "content" / "boards.yaml"

HEADER = "# Generated by scripts/build_content.py from resources/scans. Do not edit by hand.\n"
REQUIRED = ("id", "name", "suit", "set", "deck", "set_code")
ICON_RE = re.compile(r"\[([^\]]+)\]")


def split_spec(path: Path) -> tuple[dict, str]:
    text = path.read_text()
    match = re.match(r"---\n(.*?)\n---\n(.*)", text, re.S)
    if not match:
        raise ValueError(f"{path}: no frontmatter")
    return yaml.safe_load(match.group(1)), match.group(2)


def section(body: str, title: str) -> str:
    match = re.search(rf"^## {re.escape(title)}\n(.*?)(?=^## |\Z)", body, re.S | re.M)
    return match.group(1).strip() if match else ""


def printed_lines(body: str) -> list[str]:
    lines = []
    for line in section(body, "Printed text").splitlines():
        line = line.strip()
        if line.startswith(">"):
            lines.append(line.lstrip("> ").rstrip())
    return lines


def operations(body: str) -> list[dict]:
    ops = []
    for match in re.finditer(r"^### \d+\. (.+?)\n(.*?)(?=^### |^## |\Z)", section(body, "Operations") + "\n", re.S | re.M):
        kind, block = match.group(1).strip(), match.group(2)

        def field(name: str) -> str | None:
            m = re.search(rf"^- \*\*{re.escape(name)}:\*\* (.+)$", block, re.M)
            return m.group(1).strip() if m else None

        actions = re.findall(r"`([A-Z_]+)`", field("Actions used") or "")
        op = {
            "kind": kind,
            "text": field("Printed"),
            "action_cost": field("Action cost") == "yes",
            "attack": field("Attack") == "yes",
            "requires": None if field("Requires") in (None, "none") else field("Requires"),
            "cost": None if field("Cost") in (None, "none") else field("Cost"),
            "trigger": field("Trigger"),
            "uses": actions,
            "undoable": None if field("Undoable") is None else field("Undoable") == "yes",
        }
        ops.append({k: v for k, v in op.items() if v is not None and v != []})
    return ops


def build_cards() -> dict[str, list[dict]]:
    by_set: dict[str, list[dict]] = {}
    seen: dict[str, Path] = {}
    errors: list[str] = []
    for path in sorted(CARD_SPECS.rglob("*.md")):
        if path.name == "README.md":
            continue
        fm, body = split_spec(path)
        missing = [k for k in REQUIRED if not fm.get(k)]
        if missing:
            errors.append(f"{path.relative_to(ROOT)}: missing {', '.join(missing)}")
            continue
        if fm["id"] in seen:
            errors.append(f"duplicate id {fm['id']}: {seen[fm['id']]} and {path}")
            continue
        seen[fm["id"]] = path
        card = {
            "id": fm["id"],
            "name": fm["name"],
            "suit": fm["suit"],
            "deck": fm["deck"],
            "set_code": fm["set_code"],
            "box_marker": fm.get("box_marker"),
            "position": fm.get("position"),
            "traits": fm.get("traits") or [],
            "skills": fm.get("skills") or [],
            "focus": fm.get("focus"),
            "vp": fm.get("vp"),
            "away_teams": fm.get("away_teams"),
            "development_cost": fm.get("development_cost"),
            "ship_token": bool(fm.get("ship_token")),
            "image": fm["id"],
            "text": printed_lines(body),
            "operations": operations(body),
        }
        for extra in ("mode", "sequence", "starting_glory", "bot_actions"):
            if extra in fm:
                card[extra] = fm[extra]
        by_set.setdefault(fm["set"], []).append(card)
    if errors:
        raise SystemExit("Spec errors:\n" + "\n".join(f"  {e}" for e in errors))
    return by_set


def build_boards() -> list[dict]:
    boards = []
    for path in sorted(BOARD_SPECS.glob("*.md")):
        fm, body = split_spec(path)
        missions = []
        for mission in fm["missions"]:
            block = re.search(rf"^### {re.escape(mission['name'])}.*?\n(.*?)(?=^### |^## |\Z)", body, re.S | re.M)
            text = block.group(1) if block else ""
            if "Same goal and reward as the Basic side" in text:
                basic = BOARD_SPECS / f"cb-{fm['captain']}-basic.md"
                _, basic_body = split_spec(basic)
                block = re.search(rf"^### {re.escape(mission['name'])}.*?\n(.*?)(?=^### |^## |\Z)", basic_body, re.S | re.M)
                text = block.group(1) if block else ""

            def field(name: str) -> str | None:
                m = re.search(rf"^- \*\*{re.escape(name)}:\*\* (.+)$", text, re.M)
                return m.group(1).strip() if m else None

            missions.append({
                "id": mission["id"],
                "name": mission["name"],
                "vp": mission.get("vp"),
                "goal": field("Printed goal"),
                "reward": field("Printed reward"),
                "uses": re.findall(r"`([A-Z_]+)`", field("Actions used") or ""),
            })
        boards.append({
            "id": fm["id"],
            "captain": fm["captain"],
            "side": fm["side"],
            "image": fm["id"],
            "control_max": fm["turn_summary"]["control_max"],
            "actions": fm["turn_summary"]["actions"],
            "mission_completion_tokens": fm["mission_completion_tokens"],
            "tracks": {k: {int(s): m for s, m in v.items()} for k, v in fm["tracks"].items()},
            "missions": missions,
        })
    return boards


def main() -> int:
    by_set = build_cards()
    OUT_CARDS.mkdir(parents=True, exist_ok=True)
    for old in OUT_CARDS.glob("*.yaml"):
        old.unlink()
    for set_name, cards in sorted(by_set.items()):
        cards.sort(key=lambda c: c["id"])
        (OUT_CARDS / f"{set_name}.yaml").write_text(
            HEADER + yaml.safe_dump({"set": set_name, "cards": cards}, sort_keys=False, allow_unicode=True, width=120)
        )
        print(f"server/content/cards/{set_name}.yaml: {len(cards)} cards")
    boards = build_boards()
    OUT_BOARDS.write_text(HEADER + yaml.safe_dump({"boards": boards}, sort_keys=False, allow_unicode=True, width=120))
    print(f"server/content/boards.yaml: {len(boards)} board sides")
    return 0


if __name__ == "__main__":
    sys.exit(main())
